name       : libselinux
version    : 20170804
release    : 1
source     :
    - https://github.com/SELinuxProject/selinux/archive/20170804.tar.gz : 43a156eef40d790f4a66c5006cdb140601f5f83cdb76d9e0b0516f7654af95b6
license    : Public-Domain
component  : security.library
summary    :
    - SELinux runtime library
    - utils: Command line utilities for SELinux
description: |
    Main runtime library and API for the SELinux Linux Security Module.
    This package is provided in Solus with the sole purpose of providing
    ABI compatibility with "classic Snaps" in order for them to run freely
    on more platforms without limitation.

    Solus does not use SELinux within the kernel, the role of `LSM` is given
    to the AppArmor subsystem.
patterns   :
    - utils:
        - /usr/sbin
        - /usr/share/man
    - devel: /usr/share/man/man3
builddeps  :
    - pkgconfig(libsepol)
build      : |
    %make -C libselinux SHLIBDIR=%libdir% LIBDIR=%libdir%
install    : |
    %make_install -C libselinux SHLIBDIR=$installdir/%libdir% LIBDIR=$installdir/%libdir%
